services:
  
  # main application
  # run command:
  # docker compose up
  casavue:
    image: ghcr.io/czoczo/cavu:latest-alpine-nonroot
    ports:
      - "8080:8080"
    networks:
      - casavue
    volumes:
      - casavue-config:/app/config

  # enables editing main.yaml config file inside docker volume
  # run comand:
  # docker compose run edit-main && reset
  edit-main:
    image: ghcr.io/czoczo/cavu:latest-alpine-nonroot
    entrypoint: "vim"
    command: "/app/config/main.yaml"
    environment:
      COLS: $COLS
      LINES: $LINES
    volumes:
      - casavue-config:/app/config
    profiles:
      - no-auto-start
    stdin_open: true
    tty: true

  # enables editing items.yaml config file inside docker volume
  # run command:
  # docker compose run edit-main && reset
  edit-items:
    image: ghcr.io/czoczo/cavu:latest-alpine-nonroot
    entrypoint: "vim"
    command: "/app/config/items.yaml"
    environment:
      COLS: $COLS
      LINES: $LINES
    volumes:
      - casavue-config:/app/config
    profiles:
      - no-auto-start
    stdin_open: true
    tty: true

  # enables generating static HTML+JS (Vue) dashboard page
  # run command:
  # docker compose run static
  static:
    image: ghcr.io/czoczo/cavu:latest-alpine-nonroot
    command: "-static"
    profiles:
      - no-auto-start
    volumes:
      - casavue-config:/app/config
      - ./static:/app/dist

volumes:
  casavue-config:

networks:
  casavue: {}
