# static definitions of dashboard items
#
# Each item represents entry on dashboard.
# set to 'items: []' for empty list.
items:

    - # item title
      name: Duck Duck Go

      # name by which elements are aggregated
      namespace: searching

      # URL to which the element links to
      url: "https://duckduckgo.com/"

    - name: Bing
      namespace: searching
      url: "https://www.bing.com/"

    - name: Google 
      namespace: searching
      url: "https://www.google.com/"
        
    - name: Weather radar
      namespace: weather
      url: "https://www.windy.com"

    - name: Lightning & Thunderstorms
      namespace: weather
      url: "https://www.blitzortung.org"

    - name: Modele numeryczne – Model GFS
      namespace: weather
      url: "https://meteomodel.pl/modele-numeryczne-mapy-gfs/"
