name: Build and deploy CasaVue Helm Chart

on:
  push:
    branches: [ main ]
    paths: [ VERSION_CHART.txt ]
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
#permissions:
  #contents: read
  #pages: write
  #id-token: write
permissions: write-all

jobs:
  build-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run Trivy vulnerability scanner for config scan
        uses: aquasecurity/trivy-action@0.23.0
        with:
          scan-type: 'config'
          hide-progress: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
        
      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
      - name: Update Chart versions
        run: .github/scripts/update_chart_version.sh

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: deployment
          skip_existing: true
        env:
           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  trigger-pages-build-and-deploy:
    needs: build-helm-chart
    uses: ./.github/workflows/pages_build_and_deploy.yaml