name: Piaskownica

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  #push:
  #  branches: [ main ]
  #  paths: [ VERSION_APP.txt ]
  workflow_dispatch:

permissions: write-all


jobs:
  test_1:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      real_status: ${{ steps.first.outcome }}
    steps:
      - name: first
        id: first
        run: echo 'falsz' && false
      #  run: echo 'prawda'

  koniec_1:
    runs-on: ubuntu-latest
    needs: test_1
    if: needs.test_1.outputs.real_status == 'success'
    steps:
      - name: sprawdzacz
        run: echo "doszedlem!"
    
  test_2:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      real_status: ${{ steps.second.outcome }}
    steps:
      - name: second
        id: second
        run: echo 'prawda'

  koniec_2:
    runs-on: ubuntu-latest
    if: needs.test_2.outputs.real_status == 'success'
    needs: test_2
    steps:
      - name: sprawdzaczdwa
        run: echo "doszedlem dwa!"
    

  ostatecznykoniec:
    runs-on: ubuntu-latest
    needs:
      - test_1
      - test_2
    steps:
      - name: sprawdzaczostateczny
        run: echo "DOBRA BEDZIE OK! | ${{ needs.test_1.outputs.real_status }} |  | ${{ needs.test_2.outputs.real_status }} |"
    