name: Piaskownica

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  #push:
  #  branches: [ main ]
  #  paths: [ VERSION_APP.txt ]
  workflow_dispatch:

permissions: write-all


jobs:
  test_1:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      real_status: ${{ steps.first.outcome }}
    steps:
      - name: first
      #  run: echo 'prawda'
        run: echo 'falsz' && false

  koniec_1:
    runs-on: ubuntu-latest
    needs: test_1
    if: needs.test_1.outputs_real_status == 'success'
    steps:
      - name: sprawdzacz
        run: echo "doszedlem!"
    
  test_2:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: testdwa
        run: echo 'prawda'

  koniec_2:
    runs-on: ubuntu-latest
    needs: test_2
    steps:
      - name: sprawdzaczdwa
        run: echo "doszedlem dwa!"
    

  ostatecznykoniec:
    runs-on: ubuntu-latest
    needs:
      - test_1
    steps:
      - name: sprawdzaczostateczny
        run: echo "DOBRA BEDZIE OK! | ${{ needs.test_1.outputs_real_status }} |"
    